-- +goose Up
CREATE TABLE books (
    id int GENERATED BY DEFAULT AS IDENTITY,
    book_title varchar(64),
    book_year int,
    author_name varchar(64)
);

-- +goose Down
DROP TABLE books;
