-- +goose Up
CREATE TABLE journals (
    id int GENERATED BY DEFAULT AS IDENTITY,
    journal_title varchar(64),
    issue_year int,
    publisher varchar(64)
);
-- +goose Down
DROP TABLE journals;